# Generated by Django 2.1.4 on 2019-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='homepage_only',
            field=models.BooleanField(default=False),
        ),
    ]
