# Generated by Django 2.1.4 on 2019-08-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_alerts', '0002_alert_homepage_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'get_latest_by': '-updated'},
        ),
    ]
