# Generated by Django 2.1.4 on 2019-08-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_alerts', '0003_auto_20190818_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={},
        ),
    ]
