# Generated by Django 2.1.4 on 2018-12-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_visible',
        ),
    ]
