# Generated by Django 2.1.4 on 2019-01-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0005_post_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
