# Generated by Django 2.1.4 on 2019-01-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0006_post_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
