# Generated by Django 2.1.4 on 2019-01-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0007_auto_20190111_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
