# Generated by Django 2.1.4 on 2019-01-16 03:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0012_postcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comments_enabled', models.BooleanField(default=False)),
                ('minimum_word_count', models.PositiveSmallIntegerField(default=500)),
                ('minimum_tag_count', models.PositiveSmallIntegerField(default=4)),
                ('minimum_internal_link_count', models.PositiveSmallIntegerField(default=1)),
                ('minimum_external_link_count', models.PositiveSmallIntegerField(default=1)),
                ('minimum_image_count', models.PositiveSmallIntegerField(default=1)),
                ('minimum_keyword_count', models.PositiveSmallIntegerField(default=2)),
                ('seo_checks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('word_count', 'Word count'), ('tags', 'Tag count'), ('images', 'Image count'), ('internal_links', 'Internal link count'), ('external_links', 'External link count'), ('keywords', 'Keyword count')], max_length=24), size=None)),
            ],
        ),
    ]
