# Generated by Django 2.1.4 on 2019-01-16 08:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0013_postsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsettings',
            options={'verbose_name': 'Global Post Setting'},
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postsettings',
            name='seo_checks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('word_count', 'Word count'), ('tags', 'Tag count'), ('images', 'Image count'), ('internal_links', 'Internal link count'), ('external_links', 'External link count'), ('keywords', 'Keyword count')], max_length=24), default=list, size=None, verbose_name='SEO checks'),
        ),
    ]
