# Generated by Django 2.1.4 on 2019-01-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0014_auto_20190116_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date']},
        ),
    ]
