# Generated by Django 2.1.4 on 2019-08-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0017_auto_20190125_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='metadata',
            new_name='checks',
        ),
    ]
