# Generated by Django 2.1.4 on 2019-08-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0003_objectmetadata_viewmetadata'),
        ('smbs_blog', '0018_auto_20190810_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_base.ObjectMetadata'),
        ),
    ]
