# Generated by Django 2.1.4 on 2019-12-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0020_auto_20191226_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='reaction_count',
            field=models.IntegerField(default=1),
        ),
    ]
