# Generated by Django 2.1.4 on 2019-12-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0021_postcomment_reaction_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
