# Generated by Django 3.0.4 on 2020-03-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0024_auto_20200131_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='blog_metadata',
            field=models.TextField(blank=True),
        ),
    ]
