# Generated by Django 3.1.4 on 2026-01-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_blog', '0028_auto_20221225_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_alt_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
