# Generated by Django 2.1.4 on 2019-12-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_user_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostcomment',
            name='reaction_count',
            field=models.IntegerField(default=1),
        ),
    ]
