# Generated by Django 2.1.4 on 2019-12-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_user_posts', '0002_userpostcomment_reaction_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostcomment',
            old_name='post',
            new_name='user_post',
        ),
    ]
