# Generated by Django 2.1.4 on 2019-12-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_user_posts', '0004_userpostcommentreaction_userpostreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostreaction',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='smbs_user_posts.UserPost'),
        ),
    ]
