# Generated by Django 2.1.4 on 2019-12-28 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_user_posts', '0005_auto_20191228_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostcommentreaction',
            name='user_post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='smbs_user_posts.UserPostComment'),
        ),
    ]
