# Generated by Django 2.1.4 on 2019-12-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_user_posts', '0006_auto_20191228_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostcomment',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
