# Generated by Django 2.1.4 on 2019-12-30 21:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('smbs_user_posts', '0008_auto_20191229_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('default_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None, verbose_name='Default post tags')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'User Post Settings',
            },
        ),
    ]
