# Generated by Django 3.0.3 on 2020-02-24 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0007_auto_20190821_2119'),
        ('smbs_user_posts', '0010_userpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_base.ObjectMetadata'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_posts', verbose_name='Image'),
        ),
    ]
