# Generated by Django 3.0.3 on 2020-04-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_user_posts', '0011_auto_20200224_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
