# Generated by Django 3.0.5 on 2020-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_user_posts', '0012_auto_20200409_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostsettings',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_posts', verbose_name='Image'),
        ),
    ]
