# Generated by Django 2.1.4 on 2019-08-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smbs_cities_light.City'),
        ),
    ]
