# Generated by Django 2.1.4 on 2019-01-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
