# Generated by Django 3.1.1 on 2020-09-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_inventory', '0003_inventorysettings_navigation_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Items'},
        ),
    ]
