# Generated by Django 2.1.4 on 2019-01-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='smbs_logo')),
                ('google_tag_manager_script', models.TextField(blank=True)),
                ('google_tag_manager_noscript', models.TextField(blank=True)),
                ('email_host', models.CharField(max_length=255)),
                ('email_port', models.PositiveSmallIntegerField()),
                ('email_user', models.CharField(max_length=255)),
                ('email_password', models.CharField(max_length=255)),
                ('email_use_tls', models.BooleanField(default=False)),
                ('contact_display_name', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(max_length=24)),
                ('contact_email_address', models.EmailField(max_length=254)),
                ('google_maps_location_script', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
