# Generated by Django 2.1.4 on 2019-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
