# Generated by Django 2.1.4 on 2019-04-30 07:02

from django.db import migrations, models
import smbs_base.models
import smbs_base.storage


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0001_squashed_0009_auto_20190410_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesettings',
            name='icon',
            field=models.FileField(blank=True, null=True, storage=smbs_base.storage.OverwriteStorage(), upload_to=smbs_base.models.site_icon_path, validators=[smbs_base.models.validate_image_extension]),
        ),
    ]
