# Generated by Django 2.1.4 on 2019-08-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0002_basesettings_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('gplus_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_description', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('og_type', models.CharField(blank=True, max_length=255, null=True)),
                ('og_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('og_profile_id', models.CharField(blank=True, max_length=255, null=True)),
                ('og_publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('og_author_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_pages', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_type', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_site', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_author', models.CharField(blank=True, max_length=255, null=True)),
                ('published_time', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_time', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('locale', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('gplus_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_description', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('og_type', models.CharField(blank=True, max_length=255, null=True)),
                ('og_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('og_profile_id', models.CharField(blank=True, max_length=255, null=True)),
                ('og_publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('og_author_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_pages', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_type', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_site', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_author', models.CharField(blank=True, max_length=255, null=True)),
                ('published_time', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_time', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('locale', models.CharField(blank=True, max_length=255, null=True)),
                ('view', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
