# Generated by Django 2.1.4 on 2019-01-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0002_metatags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
