# Generated by Django 2.1.4 on 2019-08-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0003_objectmetadata_viewmetadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectmetadata',
            options={'get_latest_by': '-updated'},
        ),
        migrations.AlterModelOptions(
            name='viewmetadata',
            options={'get_latest_by': '-updated'},
        ),
    ]
