# Generated by Django 2.1.4 on 2019-01-19 10:42

from django.db import migrations, models
import smbs_apps.smbs_base.models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0004_auto_20190119_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=smbs_apps.smbs_base.models.site_logo_path, validators=[smbs_apps.smbs_base.models.validate_image_extension]),
        ),
    ]
