# Generated by Django 2.1.4 on 2019-08-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0005_auto_20190818_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectmetadata',
            name='gplus_title',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='gplus_title',
        ),
    ]
