# Generated by Django 2.1.4 on 2019-01-20 20:30

from django.db import migrations, models
import smbs_base.models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0005_auto_20190119_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaTags',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_css',
            field=models.FileField(blank=True, null=True, upload_to=smbs_base.models.site_css_path),
        ),
    ]
