# Generated by Django 2.1.4 on 2019-08-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0006_auto_20190818_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectmetadata',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='fb_pages',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='og_app_id',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='og_author_url',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='og_profile_id',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='og_publisher',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='published_time',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='twitter_author',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='twitter_description',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='twitter_title',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='twitter_type',
        ),
        migrations.RemoveField(
            model_name='objectmetadata',
            name='url',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='fb_pages',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='og_app_id',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='og_author_url',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='og_profile_id',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='og_publisher',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='published_time',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='twitter_author',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='twitter_description',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='twitter_title',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='twitter_type',
        ),
        migrations.RemoveField(
            model_name='viewmetadata',
            name='url',
        ),
        migrations.AddField(
            model_name='objectmetadata',
            name='og_fb_admins',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='objectmetadata',
            name='twitter_card',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='objectmetadata',
            name='twitter_creator',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='viewmetadata',
            name='og_fb_admins',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='viewmetadata',
            name='twitter_card',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='viewmetadata',
            name='twitter_creator',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='objectmetadata',
            name='description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='objectmetadata',
            name='og_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='objectmetadata',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='objectmetadata',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='viewmetadata',
            name='description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='viewmetadata',
            name='og_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='viewmetadata',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='viewmetadata',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
