# Generated by Django 2.1.4 on 2019-01-25 04:18

from django.db import migrations, models
import django.db.models.deletion
import smbs_apps.smbs_base.models
import smbs_apps.smbs_base.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('smbs_base', '0007_auto_20190124_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logo', models.FileField(blank=True, null=True, storage=smbs_apps.smbs_base.storage.OverwriteStorage(), upload_to=smbs_apps.smbs_base.models.site_logo_path, validators=[smbs_apps.smbs_base.models.validate_image_extension])),
                ('google_tag_manager_script', models.TextField(blank=True)),
                ('google_tag_manager_noscript', models.TextField(blank=True)),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('email_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_password', models.CharField(blank=True, max_length=255, null=True)),
                ('email_use_tls', models.BooleanField(default=False)),
                ('contact_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=24, null=True)),
                ('contact_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('google_maps_location_script', models.TextField(blank=True)),
                ('custom_css', models.FileField(blank=True, null=True, storage=smbs_apps.smbs_base.storage.OverwriteStorage(), upload_to=smbs_apps.smbs_base.models.site_css_path)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
