# Generated by Django 3.0.4 on 2020-03-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0007_auto_20190821_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basesettings',
            old_name='google_tag_manager_noscript',
            new_name='global_metadata',
        ),
        migrations.RemoveField(
            model_name='basesettings',
            name='google_tag_manager_script',
        ),
    ]
