# Generated by Django 2.1.4 on 2019-04-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0008_auto_20190125_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesettings',
            name='contact_display_name',
        ),
        migrations.RemoveField(
            model_name='basesettings',
            name='contact_email_address',
        ),
        migrations.RemoveField(
            model_name='basesettings',
            name='contact_phone_number',
        ),
        migrations.RemoveField(
            model_name='basesettings',
            name='google_maps_location_script',
        ),
    ]
