# Generated by Django 3.1.1 on 2020-09-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0010_auto_20200921_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesettings',
            name='navbar_type',
            field=models.CharField(choices=[('navbar_dark', 'Dark'), ('navbar_light', 'Light')], default='navbar_light', max_length=64),
        ),
    ]
