# Generated by Django 3.1.1 on 2020-12-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0011_auto_20200921_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesettings',
            name='custom_css',
            field=models.FileField(blank=True, null=True, upload_to='site/css'),
        ),
    ]
