# Generated by Django 3.1.4 on 2026-01-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0012_auto_20201203_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmetadata',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='objectmetadata',
            name='keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='objectmetadata',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='viewmetadata',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='viewmetadata',
            name='keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='viewmetadata',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
