# Generated by Django 3.1.1 on 2020-12-16 04:29

from django.db import migrations, models
import django.db.models.deletion
import smbs_apps.smbs_forms.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Form Settings',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name', max_length=60)),
                ('email', models.EmailField(help_text='E-mail Address', max_length=254)),
                ('phone', models.CharField(help_text='Phone Number', max_length=20, validators=[smbs_apps.smbs_forms.validators.validate_phone])),
                ('message', models.TextField(help_text='Message')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Contact Form',
            },
        ),
    ]
