# Generated by Django 3.1.1 on 2020-12-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('smbs_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_user', models.CharField(blank=True, max_length=64, null=True)),
                ('email_password', models.CharField(blank=True, max_length=64, null=True)),
                ('success_url', models.URLField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Form Settings',
            },
        ),
        migrations.DeleteModel(
            name='FormSettings',
        ),
    ]
