# Generated by Django 3.1.1 on 2020-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_forms', '0002_auto_20201217_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformsettings',
            options={'verbose_name': 'Contact Form Settings'},
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='email_host',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
