# Generated by Django 3.1.1 on 2020-12-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_forms', '0003_auto_20201217_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsettings',
            name='email_port',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
