# Generated by Django 3.1.1 on 2020-12-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_forms', '0004_contactformsettings_email_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsettings',
            name='email_recipient',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='email_subject',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
