# Generated by Django 3.1.1 on 2020-12-21 19:52

from django.db import migrations, models
import django.db.models.deletion
import smbs_forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('smbs_forms', '0005_auto_20201217_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Name', max_length=64),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Phone Number', max_length=24, validators=[smbs_forms.validators.validate_phone]),
        ),
        migrations.CreateModel(
            name='ContactWithAddressFormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=64, null=True)),
                ('email_recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_user', models.CharField(blank=True, max_length=64, null=True)),
                ('email_password', models.CharField(blank=True, max_length=64, null=True)),
                ('email_host', models.CharField(blank=True, max_length=64, null=True)),
                ('email_port', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success_url', models.URLField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Contact Form With Address Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactWithAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name', max_length=64)),
                ('email', models.EmailField(help_text='E-mail Address', max_length=254)),
                ('phone', models.CharField(help_text='Phone Number', max_length=24, validators=[smbs_forms.validators.validate_phone])),
                ('address', models.CharField(help_text='Address', max_length=128)),
                ('city', models.CharField(help_text='City', max_length=64)),
                ('state', models.CharField(help_text='State', max_length=32)),
                ('message', models.TextField(help_text='Message')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Contact Form With Address',
            },
        ),
    ]
