# Generated by Django 3.1.4 on 2021-02-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0026_auto_20201221_2011'),
        ('smbs_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='login_redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to='smbs_pages.page'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='signup_redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup', to='smbs_pages.page'),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='privacy_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='smbs_pages.page'),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='terms_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos', to='smbs_pages.page'),
        ),
    ]
