# Generated by Django 2.1.4 on 2020-01-09 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_base', '0007_auto_20190821_2119'),
        ('smbs_pages', '0003_auto_20200109_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_base.ObjectMetadata'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_pages.Page'),
        ),
    ]
