# Generated by Django 2.1.4 on 2020-01-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0004_auto_20200109_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('custom_classes', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('position', models.CharField(choices=[(1, 'Right'), (2, 'Left')], default=1, max_length=8)),
                ('width', models.CharField(choices=[(3, '25%'), (6, '50%'), (9, '75%'), (12, '100%')], default=12, max_length=2)),
                ('mobile_width', models.CharField(choices=[(3, '25%'), (6, '50%'), (9, '75%'), (12, '100%')], default=12, max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('custom_classes', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('position', models.CharField(choices=[(1, 'Above'), (2, 'Below')], default=2, max_length=8)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('page', models.ManyToManyField(to='smbs_pages.Page')),
                ('position_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_pages.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='page-media/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('custom_classes', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('position', models.CharField(choices=[(1, 'Above'), (2, 'Below')], default=2, max_length=8)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('container', models.ManyToManyField(to='smbs_pages.Container')),
                ('position_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_pages.Row')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('custom_classes', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('html', 'HTML'), ('headline', 'Headline'), ('paragraph', 'Paragraph'), ('title_paragraph', 'Title and paragraph'), ('image', 'Image'), ('image_text', 'Image with text')], default='paragraph', max_length=16)),
                ('content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('column', models.ManyToManyField(to='smbs_pages.Column')),
                ('media', models.ManyToManyField(to='smbs_pages.Media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='column',
            name='container',
            field=models.ManyToManyField(to='smbs_pages.Container'),
        ),
        migrations.AddField(
            model_name='column',
            name='position_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_pages.Column'),
        ),
    ]
