# Generated by Django 2.1.4 on 2020-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0006_auto_20200111_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='container',
        ),
        migrations.AddField(
            model_name='column',
            name='row',
            field=models.ManyToManyField(to='smbs_pages.Row'),
        ),
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.CharField(choices=[(1, 'Right'), (2, 'Left')], default=2, max_length=8),
        ),
    ]
