# Generated by Django 2.1.4 on 2020-01-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0007_auto_20200111_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='column',
            field=models.ManyToManyField(blank=True, to='smbs_pages.Column'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='media',
            field=models.ManyToManyField(blank=True, to='smbs_pages.Media'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('html', 'HTML'), ('headline', 'Headline'), ('paragraph', 'Paragraph'), ('markdown', 'Markdown'), ('image', 'Image'), ('image_text', 'Image with text')], default='paragraph', max_length=16),
        ),
    ]
