# Generated by Django 2.1.4 on 2020-01-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0008_auto_20200113_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='navigation_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
