# Generated by Django 2.1.4 on 2020-01-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0009_page_navigation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.CharField(choices=[(1, 'Right'), (2, 'Left')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='container',
            name='position',
            field=models.CharField(choices=[(1, 'Above'), (2, 'Below')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='row',
            name='position',
            field=models.CharField(choices=[(1, 'Above'), (2, 'Below')], default=2, max_length=1),
        ),
    ]
