# Generated by Django 3.0.2 on 2020-01-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0010_auto_20200131_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Above'), (2, 'Left'), (3, 'Right'), (4, 'Below')], default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Above'), (2, 'Left'), (3, 'Right'), (4, 'Below')], default=0),
        ),
        migrations.AlterField(
            model_name='row',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Above'), (2, 'Left'), (3, 'Right'), (4, 'Below')], default=0),
        ),
    ]
