# Generated by Django 3.0.2 on 2020-01-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0011_auto_20200131_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='mobile_width',
            field=models.PositiveSmallIntegerField(choices=[(3, '25%'), (6, '50%'), (9, '75%'), (12, '100%')], default=12),
        ),
        migrations.AlterField(
            model_name='column',
            name='width',
            field=models.PositiveSmallIntegerField(choices=[(3, '25%'), (6, '50%'), (9, '75%'), (12, '100%')], default=12),
        ),
    ]
