# Generated by Django 3.0.3 on 2020-02-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0012_auto_20200131_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='navigation_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('widget_html', 'HTML'), ('widget_headline', 'Headline'), ('widget_paragraph', 'Paragraph'), ('widget_markdown', 'Markdown'), ('widget_image', 'Image')], default='widget_paragraph', max_length=16),
        ),
    ]
