# Generated by Django 3.0.3 on 2020-02-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0013_auto_20200210_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlineWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smbs_pages.Widget')),
            ],
            options={
                'abstract': False,
            },
            bases=('smbs_pages.widget',),
        ),
        migrations.CreateModel(
            name='HTMLWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smbs_pages.Widget')),
            ],
            options={
                'abstract': False,
            },
            bases=('smbs_pages.widget',),
        ),
        migrations.CreateModel(
            name='MarkdownWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smbs_pages.Widget')),
            ],
            options={
                'abstract': False,
            },
            bases=('smbs_pages.widget',),
        ),
        migrations.CreateModel(
            name='ParagraphWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smbs_pages.Widget')),
            ],
            options={
                'abstract': False,
            },
            bases=('smbs_pages.widget',),
        ),
        migrations.RemoveField(
            model_name='widget',
            name='type',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='page/media/'),
        ),
    ]
