# Generated by Django 3.0.3 on 2020-04-09 07:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0015_auto_20200326_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='version',
        ),
        migrations.AddField(
            model_name='widget',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('html', 'Raw HTML'), ('markdown', 'Markdown'), ('paragraph', 'Paragraph'), ('headline', 'Headline'), ('blog_posts', 'Blog Posts')], default='paragraph', max_length=16),
        ),
    ]
