# Generated by Django 3.1.1 on 2020-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0016_auto_20200409_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('smbs_blog.smbs_widgets.blog_posts', 'Blog Posts'), ('smbs_pages.smbs_widgets.headline', 'Headline'), ('smbs_pages.smbs_widgets.html', 'Raw HTML'), ('smbs_pages.smbs_widgets.markdown', 'Markdown'), ('smbs_pages.smbs_widgets.paragraph', 'Paragraph')], max_length=128),
        ),
    ]
