# Generated by Django 3.1.1 on 2020-09-13 21:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0017_auto_20200913_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
