# Generated by Django 3.1.1 on 2020-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0019_auto_20200916_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('smbs_blog.smbs_widgets.blog_posts', 'Blog Posts'), ('smbs_pages.smbs_widgets.headline', 'Headline'), ('smbs_pages.smbs_widgets.html', 'Raw HTML'), ('smbs_pages.smbs_widgets.image', 'Image'), ('smbs_pages.smbs_widgets.markdown', 'Markdown'), ('smbs_pages.smbs_widgets.paragraph', 'Paragraph'), ('smbs_inventory.smbs_widgets.inventory_items', 'Blog Posts')], max_length=128),
        ),
    ]
