# Generated by Django 3.1.1 on 2020-09-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0021_auto_20200922_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Above'), (2, 'Left'), (3, 'Right'), (4, 'Below')], default=0),
        ),
        migrations.AddField(
            model_name='widget',
            name='position_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_pages.widget'),
        ),
    ]
