# Generated by Django 3.1.1 on 2020-12-03 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('smbs_pages', '0022_auto_20200923_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='is_active',
            new_name='active',
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='smbs_pages/files')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smbs_pages.template'),
        ),
    ]
