# Generated by Django 3.1.4 on 2022-12-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0028_auto_20210716_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('smbs_apps.smbs_blog.smbs_widgets.blog_posts', 'Blog Posts'), ('smbs_apps.smbs_pages.smbs_widgets.headline', 'Headline'), ('smbs_apps.smbs_pages.smbs_widgets.html', 'Raw HTML'), ('smbs_apps.smbs_pages.smbs_widgets.image', 'Image'), ('smbs_apps.smbs_pages.smbs_widgets.markdown', 'Markdown'), ('smbs_apps.smbs_pages.smbs_widgets.paragraph', 'Paragraph'), ('smbs_apps.smbs_inventory.smbs_widgets.inventory_items', 'Inventory Items'), ('smbs_apps.smbs_forms.smbs_widgets.contact_address_form', 'Contact Form With Address'), ('smbs_apps.smbs_forms.smbs_widgets.contact_form', 'Contact Form')], max_length=128),
        ),
    ]
