# Generated by Django 3.1.4 on 2026-01-30 02:53

from django.db import migrations, models
import smbs_apps.smbs_pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0031_auto_20241008_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=smbs_apps.smbs_pages.models.media_upload_to),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('smbs_apps.smbs_blog.smbs_widgets.blog_posts', 'Blog Posts'), ('smbs_apps.smbs_pages.smbs_widgets.headline', 'Headline'), ('smbs_apps.smbs_pages.smbs_widgets.html', 'Raw HTML'), ('smbs_apps.smbs_pages.smbs_widgets.image', 'Image'), ('smbs_apps.smbs_pages.smbs_widgets.markdown', 'Markdown'), ('smbs_apps.smbs_pages.smbs_widgets.paragraph', 'Paragraph'), ('smbs_apps.smbs_inventory.smbs_widgets.inventory_items', 'Inventory Items'), ('smbs_apps.smbs_forms.smbs_widgets.contact_address_form', 'Contact Form With Address'), ('smbs_apps.smbs_forms.smbs_widgets.contact_form', 'Contact Form')], max_length=128),
        ),
    ]
