# Generated by Django 3.1.4 on 2026-01-30 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0032_auto_20260130_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='nav_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nav_children', to='smbs_pages.page'),
        ),
    ]
