# Generated by Django 6.0.6 on 2026-08-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbs_pages', '0034_alter_column_id_alter_container_id_alter_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='external_url',
            field=models.URLField(blank=True, help_text='If set, this page has no content of its own — the navbar links straight to this URL instead.', null=True),
        ),
    ]
